name: Release
on:
  push:
    braches:
      - 'master'
    paths:
      - 'CHANGELOG.md'
  pull_request:
    braches:
      - 'master'
    paths:
      - 'CHANGELOG.md'

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: https://registry.npmjs.org
      - name: Install project dependencies
        run: yarn install --frozen-lockfile
      - name: Run test
        run: yarn test
      - name: Run build
        run: yarn build
      - name: Publish project
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}